databases:
  - name: college-events-db
    databaseName: college_events
    user: college_events_user

services:
  - type: web
    name: college-event-statistics-portal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: college-events-db
          property: connectionString
